export const SELECTED_GIFIMAGE = "SELECTED_GIFIMAGE";
export const UPDATE_GIFBU_DATA = "UPDATE_GIFBU_DATA";
export const READ_GIFBU_DATA = "READ_GIFBU_DATA";
export const SAVE_GIFBU_DATA = "SAVE_GIFBU_DATA";
