export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const READ_SETTINGS = "READ_SETTINGS";
export const SAVE_SETTINGS = "SAVE_SETTINGS";

export const SELECTED_MAIL = "SELECTED_MAIL";

export const UPDATE_MAILLIST = "UPDATE_MAILLIST";
export const READ_MAILLIST = "READ_MAILLIST";
export const SAVE_MAILLIST = "SAVE_MAILLIST";

export const UPDATE_CURRENTMAIL = "UPDATE_CURRENTMAIL";

