export const SELECTED_KEYBUTTON = "SELECTED_KEYBUTTON";
export const UPDATE_KEYBUTTON = "UPDATE_KEYBUTTON";
export const READ_KEYBUTTONS = "READ_KEYBUTTONS";
export const UPDATE_MACHINE_STATUS = "UPDATE_MACHINE_STATUS";
